// export const SERVICES = [
//   {
//     id: "research-guidance",
//     icon: "🔬",
//     title: "Research Guidance",
//     tagline: "From idea to investigation — we guide every step.",
//     desc: "We help students lay a strong academic foundation by assisting in all aspects of research initiation, from choosing the right topic to building a credible conceptual framework.",
//     items: [
//       { name: "Topic Selection Assistance",             detail: "We help you identify a relevant, feasible, and impactful research topic aligned with your academic goals and current literature." },
//       { name: "Research Problem Formulation",           detail: "Translate broad areas of interest into a precise, well-defined research problem suitable for scholarly investigation." },
//       { name: "Aims & Objectives Development",          detail: "Craft clear, measurable aims and SMART objectives that define the scope and direction of your research." },
//       { name: "Hypothesis Formulation",                 detail: "Develop testable hypotheses grounded in theory and prior literature for quantitative or mixed-methods studies." },
//       { name: "Research Gap Identification",            detail: "Conduct thorough literature mapping to identify genuine gaps and contribute original knowledge to your field." },
//       { name: "Literature Review Support",              detail: "Systematic, thematic, and narrative reviews structured to critically evaluate existing scholarship." },
//       { name: "Conceptual/Theoretical Framework Building", detail: "Build logically sound frameworks that anchor your research in established theory and scholarly debate." },
//     ],
//   },
//   {
//     id: "dissertation-thesis",
//     icon: "📝",
//     title: "Dissertation / Thesis Support",
//     tagline: "Chapter by chapter, we help you write with confidence.",
//     desc: "Our structured dissertation and thesis support covers everything from planning your document to final formatting, ensuring your submission meets the highest academic standards.",
//     items: [
//       { name: "Structure of Dissertation",             detail: "Guidance on organising your dissertation logically according to university and discipline-specific requirements." },
//       { name: "Introduction Chapter",                  detail: "Craft a compelling introduction that contextualises your study, states the problem, and outlines the research approach." },
//       { name: "Review of Literature",                  detail: "Develop a comprehensive, critically analysed literature review that positions your work within the existing body of knowledge." },
//       { name: "Research Methodology",                  detail: "Justify and explain your chosen research design, methods, tools, and ethical considerations in detail." },
//       { name: "Data Collection & Analysis",            detail: "Support for primary and secondary data collection strategies, and detailed analytical techniques and interpretation." },
//       { name: "Results & Discussion",                  detail: "Present findings clearly and discuss their significance in relation to your research questions and prior literature." },
//       { name: "Conclusion & Suggestions",              detail: "Summarise insights, highlight contributions, acknowledge limitations, and suggest directions for future research." },
//       { name: "Editing & Formatting Guidelines",       detail: "Ensure your document follows university formatting standards — margins, headings, citations, referencing, and layout." },
//       { name: "Plagiarism Check & Reduction Support",  detail: "Use Turnitin / iThenticate tools and expert paraphrasing guidance to reduce similarity index to acceptable levels." },
//     ],
//   },
//   {
//     id: "research-methodology",
//     icon: "📐",
//     title: "Research Methodology",
//     tagline: "Rigorous design for credible, publishable research.",
//     desc: "A robust research methodology is the backbone of scholarly work. We guide students in selecting and applying the most appropriate methods for their research questions.",
//     items: [
//       { name: "Qualitative Methods",               detail: "Interviews, focus groups, ethnography, case studies — designed to explore meanings, experiences, and social phenomena." },
//       { name: "Quantitative Methods",              detail: "Surveys, experiments, and statistical modelling to test hypotheses and measure relationships between variables." },
//       { name: "Mixed Methods",                     detail: "Integrated approaches combining quantitative and qualitative data for a richer, multi-dimensional understanding." },
//       { name: "Sampling Techniques",               detail: "Probability and non-probability sampling strategies — random, stratified, purposive, snowball, and more." },
//       { name: "Research Design",                   detail: "Exploratory, descriptive, explanatory, experimental, and longitudinal designs matched to your research objectives." },
//       { name: "Questionnaire / Interview Guide Development", detail: "Professionally designed, validated instruments with appropriate question types, scales, and reliability checks." },
//     ],
//   },
//   {
//     id: "data-analysis",
//     icon: "📊",
//     title: "Data Analysis",
//     tagline: "Turn raw data into meaningful academic insights.",
//     desc: "Our data analysis experts support students with both statistical and qualitative analysis, helping them interpret results accurately and present findings effectively.",
//     items: [
//       { name: "Statistical Tools (SPSS, STATA, R, Excel)", detail: "Hands-on support with descriptive statistics, regression, ANOVA, factor analysis, SEM, and more using leading software." },
//       { name: "Qualitative Analysis (NVivo, Thematic Analysis)", detail: "Systematic coding, theme development, and pattern identification from interview, survey, or documentary data." },
//       { name: "Data Interpretation Support",        detail: "Expert interpretation of tables, outputs, and findings to ensure they are accurately aligned with your research questions." },
//       { name: "Graphs, Charts & Visualizations",   detail: "Professional, publication-ready charts, graphs, and infographics that communicate your data clearly and effectively." },
//       { name: "Coding & Theme Development",         detail: "Guided open, axial, and selective coding for grounded theory, and thematic analysis for qualitative datasets." },
//     ],
//   },
//   {
//     id: "writing-editing",
//     icon: "✏️",
//     title: "Writing & Editing Services",
//     tagline: "Polished prose that meets the highest academic standards.",
//     desc: "Our expert academic writers and editors transform your drafts into clear, coherent, and publication-ready documents — improving both content quality and language precision.",
//     items: [
//       { name: "Academic Writing Assistance",         detail: "Support at every stage — from outlining and drafting to argumentation, critical thinking, and scholarly tone." },
//       { name: "Grammar & Language Improvement",     detail: "Comprehensive language editing for non-native English speakers to ensure clarity, correctness, and fluency." },
//       { name: "Formatting (APA / MLA / University Style)", detail: "Accurate citation formatting, reference list construction, and document layout as per APA 7th, MLA 9th, or custom university guidelines." },
//       { name: "Proofreading",                       detail: "Final-stage review for spelling, punctuation, grammatical errors, and typographical inconsistencies before submission." },
//       { name: "Plagiarism Correction",              detail: "Strategic rewriting, paraphrasing, and citation insertion to ensure originality without compromising the meaning." },
//     ],
//   },
//   {
//     id: "publication-support",
//     icon: "📰",
//     title: "Publication Support",
//     tagline: "Get your research the recognition it deserves.",
//     desc: "From selecting the right journal to preparing a revision-ready manuscript, we guide students through the entire academic publishing process with expert precision.",
//     items: [
//       { name: "Journal Selection Support",          detail: "Match your research with the right Scopus, SCI, SSCI, or UGC-CARE listed journals for maximum visibility and acceptance." },
//       { name: "Paper Writing Guidance",             detail: "Structure and write research papers that meet journal formatting, word count, and academic writing expectations." },
//       { name: "Conference Paper Preparation",       detail: "Prepare and present high-quality conference papers for national and international academic conferences." },
//       { name: "Manuscript Editing",                 detail: "In-depth editing of submitted drafts for language, structure, argumentation, and compliance with journal guidelines." },
//       { name: "Indexing (Scopus, WoS, UGC-CARE)",  detail: "Guidance on submitting to indexed journals and understanding the criteria and benefits of each indexing body." },
//       { name: "Avoiding Predatory Journals",        detail: "Learn how to identify legitimate journals using Beall's List, DOAJ, and publisher verification strategies." },
//     ],
//   },
//   {
//     id: "training-support",
//     icon: "🎓",
//     title: "Training Support",
//     tagline: "Skill-building programs designed for the modern researcher.",
//     desc: "Our structured training programs bridge the gap between academic theory and practical research skills, offering both certified and hands-on learning experiences.",
//     items: [
//       { name: "Short-Term Training Programs",  detail: "Focused 1–4 week intensive programs on specific research skills — methodology, writing, tools, and publication." },
//       { name: "Certificate Courses",           detail: "Accredited certificate programs on academic research, data analysis, statistical tools, and scholarly writing." },
//       { name: "Field Training",                detail: "On-site learning experiences that connect theoretical knowledge with practical research environments and real-world data." },
//       { name: "Industrial Training",           detail: "Collaborative training with industry partners to develop applied research skills relevant to professional settings." },
//       { name: "Hands-On Training",             detail: "Live, practical sessions using software tools (SPSS, R, NVivo, Turnitin) and workshop-based skill development." },
//     ],
//   },
// ];

// export const PROCESS = [
//   { step: "01", title: "Initial Consultation",   desc: "Discuss your academic needs, timeline, and goals with our expert advisors — free of charge." },
//   { step: "02", title: "Customised Plan",         desc: "We design a personalised support plan tailored to your research stage and requirements." },
//   { step: "03", title: "Expert Assignment",       desc: "You're matched with the most suitable domain expert from our experienced academic team." },
//   { step: "04", title: "Ongoing Guidance",        desc: "Regular sessions, feedback loops, and milestone tracking to keep your progress on schedule." },
//   { step: "05", title: "Review & Refinement",     desc: "Iterative reviews ensure your work meets institutional and publication-grade standards." },
//   { step: "06", title: "Final Delivery",          desc: "Polished, submission-ready output delivered confidentially and on time — every time." },
// ];


export const SERVICES = [
  {
    id: "research-guidance",
    icon: "🔬",
    title: "Research Guidance",
    tagline: "From idea to investigation — we guide every step.",
    desc: "We help students lay a strong academic foundation by assisting in all aspects of research initiation, from choosing the right topic to building a credible conceptual framework.",
    items: [
      { name: "Topic Selection Assistance",             detail: "We help you identify a relevant, feasible, and impactful research topic aligned with your academic goals and current literature." },
      { name: "Research Problem Formulation",           detail: "Translate broad areas of interest into a precise, well-defined research problem suitable for scholarly investigation." },
      { name: "Aims & Objectives Development",          detail: "Craft clear, measurable aims and SMART objectives that define the scope and direction of your research." },
      { name: "Hypothesis Formulation",                 detail: "Develop testable hypotheses grounded in theory and prior literature for quantitative or mixed-methods studies." },
      { name: "Research Gap Identification",            detail: "Conduct thorough literature mapping to identify genuine gaps and contribute original knowledge to your field." },
      { name: "Literature Review Support",              detail: "Systematic, thematic, and narrative reviews structured to critically evaluate existing scholarship." },
      { name: "Conceptual/Theoretical Framework Building", detail: "Build logically sound frameworks that anchor your research in established theory and scholarly debate." },
    ],
  },
  {
    id: "dissertation-thesis",
    icon: "📝",
    title: "Dissertation / Thesis Support",
    tagline: "Chapter by chapter, we help you write with confidence.",
    desc: "Our structured dissertation and thesis support covers everything from planning your document to final formatting, ensuring your submission meets the highest academic standards.",
    items: [
      { name: "Structure of Dissertation",             detail: "Guidance on organising your dissertation logically according to university and discipline-specific requirements." },
      { name: "Introduction Chapter",                  detail: "Craft a compelling introduction that contextualises your study, states the problem, and outlines the research approach." },
      { name: "Review of Literature",                  detail: "Develop a comprehensive, critically analysed literature review that positions your work within the existing body of knowledge." },
      { name: "Research Methodology",                  detail: "Justify and explain your chosen research design, methods, tools, and ethical considerations in detail." },
      { name: "Data Collection & Analysis",            detail: "Support for primary and secondary data collection strategies, and detailed analytical techniques and interpretation." },
      { name: "Results & Discussion",                  detail: "Present findings clearly and discuss their significance in relation to your research questions and prior literature." },
      { name: "Conclusion & Suggestions",              detail: "Summarise insights, highlight contributions, acknowledge limitations, and suggest directions for future research." },
      { name: "Editing & Formatting Guidelines",       detail: "Ensure your document follows university formatting standards — margins, headings, citations, referencing, and layout." },
      { name: "Plagiarism Check & Reduction Support",  detail: "Use Turnitin / iThenticate tools and expert paraphrasing guidance to reduce similarity index to acceptable levels." },
    ],
  },
  {
    id: "research-methodology",
    icon: "📐",
    title: "Research Methodology",
    tagline: "Rigorous design for credible, publishable research.",
    desc: "A robust research methodology is the backbone of scholarly work. We guide students in selecting and applying the most appropriate methods for their research questions.",
    items: [
      { name: "Qualitative Methods",               detail: "Interviews, focus groups, ethnography, case studies — designed to explore meanings, experiences, and social phenomena." },
      { name: "Quantitative Methods",              detail: "Surveys, experiments, and statistical modelling to test hypotheses and measure relationships between variables." },
      { name: "Mixed Methods",                     detail: "Integrated approaches combining quantitative and qualitative data for a richer, multi-dimensional understanding." },
      { name: "Sampling Techniques",               detail: "Probability and non-probability sampling strategies — random, stratified, purposive, snowball, and more." },
      { name: "Research Design",                   detail: "Exploratory, descriptive, explanatory, experimental, and longitudinal designs matched to your research objectives." },
      { name: "Questionnaire / Interview Guide Development", detail: "Professionally designed, validated instruments with appropriate question types, scales, and reliability checks." },
    ],
  },
  {
    id: "data-analysis",
    icon: "📊",
    title: "Data Analysis",
    tagline: "Turn raw data into meaningful academic insights.",
    desc: "Our data analysis experts support students with both statistical and qualitative analysis, helping them interpret results accurately and present findings effectively.",
    items: [
      { name: "Statistical Tools (SPSS, STATA, R, Excel)", detail: "Hands-on support with descriptive statistics, regression, ANOVA, factor analysis, SEM, and more using leading software." },
      { name: "Qualitative Analysis (NVivo, Thematic Analysis)", detail: "Systematic coding, theme development, and pattern identification from interview, survey, or documentary data." },
      { name: "Data Interpretation Support",        detail: "Expert interpretation of tables, outputs, and findings to ensure they are accurately aligned with your research questions." },
      { name: "Graphs, Charts & Visualizations",   detail: "Professional, publication-ready charts, graphs, and infographics that communicate your data clearly and effectively." },
      { name: "Coding & Theme Development",         detail: "Guided open, axial, and selective coding for grounded theory, and thematic analysis for qualitative datasets." },
    ],
  },
  {
    id: "writing-editing",
    icon: "✏️",
    title: "Writing & Editing Services",
    tagline: "Polished prose that meets the highest academic standards.",
    desc: "Our expert academic writers and editors transform your drafts into clear, coherent, and publication-ready documents — improving both content quality and language precision.",
    items: [
      { name: "Academic Writing Assistance",         detail: "Support at every stage — from outlining and drafting to argumentation, critical thinking, and scholarly tone." },
      { name: "Grammar & Language Improvement",     detail: "Comprehensive language editing for non-native English speakers to ensure clarity, correctness, and fluency." },
      { name: "Formatting (APA / MLA / University Style)", detail: "Accurate citation formatting, reference list construction, and document layout as per APA 7th, MLA 9th, or custom university guidelines." },
      { name: "Proofreading",                       detail: "Final-stage review for spelling, punctuation, grammatical errors, and typographical inconsistencies before submission." },
      { name: "Plagiarism Correction",              detail: "Strategic rewriting, paraphrasing, and citation insertion to ensure originality without compromising the meaning." },
    ],
  },
  {
    id: "publication-support",
    icon: "📰",
    title: "Publication Support",
    tagline: "Get your research the recognition it deserves.",
    desc: "From selecting the right journal to preparing a revision-ready manuscript, we guide students through the entire academic publishing process with expert precision.",
    items: [
      { name: "Journal Selection Support",          detail: "Match your research with the right Scopus, SCI, SSCI, or UGC-CARE listed journals for maximum visibility and acceptance." },
      { name: "Paper Writing Guidance",             detail: "Structure and write research papers that meet journal formatting, word count, and academic writing expectations." },
      { name: "Conference Paper Preparation",       detail: "Prepare and present high-quality conference papers for national and international academic conferences." },
      { name: "Manuscript Editing",                 detail: "In-depth editing of submitted drafts for language, structure, argumentation, and compliance with journal guidelines." },
      { name: "Indexing (Scopus, WoS, UGC-CARE)",  detail: "Guidance on submitting to indexed journals and understanding the criteria and benefits of each indexing body." },
      { name: "Avoiding Predatory Journals",        detail: "Learn how to identify legitimate journals using Beall's List, DOAJ, and publisher verification strategies." },
    ],
  },
  {
    id: "training-support",
    icon: "🎓",
    title: "Training & Placement Support",
    tagline: "Skill-building programs designed for the modern researcher.",
    desc: "Our structured training programs bridge the gap between academic theory and practical research skills, offering both certified and hands-on learning experiences.",
    items: [
      { name: "Short-Term Training Programs",  detail: "Focused 1–4 week intensive programs on specific research skills — methodology, writing, tools, and publication." },
      { name: "Certificate Courses",           detail: "Accredited certificate programs on academic research, data analysis, statistical tools, and scholarly writing." },
      { name: "Field Training",                detail: "On-site learning experiences that connect theoretical knowledge with practical research environments and real-world data." },
      { name: "Industrial Training",           detail: "Collaborative training with industry partners to develop applied research skills relevant to professional settings." },
      { name: "Hands-On Training",             detail: "Live, practical sessions using software tools (SPSS, R, NVivo, Turnitin) and workshop-based skill development." },
    ],
  },
];

export const PROCESS = [
  { step: "01", title: "Initial Consultation",   desc: "Discuss your academic needs, timeline, and goals with our expert advisors — free of charge." },
  { step: "02", title: "Customised Plan",         desc: "We design a personalised support plan tailored to your research stage and requirements." },
  { step: "03", title: "Expert Assignment",       desc: "You're matched with the most suitable domain expert from our experienced academic team." },
  { step: "04", title: "Ongoing Guidance",        desc: "Regular sessions, feedback loops, and milestone tracking to keep your progress on schedule." },
  { step: "05", title: "Review & Refinement",     desc: "Iterative reviews ensure your work meets institutional and publication-grade standards." },
  { step: "06", title: "Final Delivery",          desc: "Polished, submission-ready output delivered confidentially and on time — every time." },
];